### ISSUE TITLE
Why cookies?

### ISSUE THREAD

**Issue by pedrualves** [afucher/hapi-pg-cookie-auth#1]
@afucher, why cookie and not web data storage?

**Comment by afucher** [comment]
web data storage == html5 local Storage ?

I think that Cookies is the most 'secure' way to do this in Browser, using the http-only flag you avoid the most ways to stole the Cookie... (I just ask to other people and read a little about, I don't know much about authentication)

Why do you ask about web data storage? Any comment? Experience?

**Comment by pedrualves** [comment]
look this:

- http://stackoverflow.com/questions/3220660/local-storage-vs-cookies
- http://wonko.com/post/why-you-probably-shouldnt-use-cookies-to-store-session-data
- https://blog.newrelic.com/2012/09/18/html5-web-storage-cookies-are-so-1994/
- http://blog.teamtreehouse.com/storing-data-on-the-client-with-localstorage
- https://en.wikipedia.org/wiki/Web_storage

**Comment by afucher** [comment]
@pedrualves I read a few of this links, and I really don't see why not use Cookie for auth, For storage data, I could use local Storage, but for auth.. I will need to make some lib to persist the data in local storage?!
Or If you mean to use JWT and store it in local storage, I read this another day: http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

**Comment by pedrualves** [comment]
> I will need to make some lib to persist the data in local storage?!
only js you can use local storage

I guesse JWT is a good choice
